### ISSUE TITLE
Please cease scanning the internet

### ISSUE THREAD

**Issue by binford2k** [augustoolucas/security-smells#1]
This scanner is incredibly disruptive. Please cease operations and contact Puppet and Vox Pupuli for advice before attempting to scan again.

**Comment by augustoolucas** [comment]
Hi Ben,

We'd like to apologize for any inconvenience. We tried to do this as non-annoying as possible by limiting a maximum of 7 issues per repository, one per each type of security smell/type of vulnerability. However, we acknowledge that we didn't think about users like Vox Pupuli, with 200+ repositories.

The cases raised were all automatically detected by a [tool](https://github.com/akondrahman/IacSec) published at a SE research conference ([icse19](https://dl.acm.org/doi/pdf/10.1109/ICSE.2019.00033)).

The tool automatically detects 7 different types of vulnerabilities in puppet scripts. We are trying to do a larger study on the tool's performance and confirm with the owners of the code (the ones with a better understanding of the environment) if the problems detected are security vulnerabilities or not. Thus, we can hopefully understand how to improve the scanner and make it better for the community.

I'm sorry about this situation, the scanner has been stopped. We highly appreciate your time! We'll contact you soon, thank you for your feedback.
